[workspace]
members = [
    "bins/gen_test_bin",
    "bins/mrc_dis",
    "bins/mrc_emu",
    "bins/mz_inspect",
    "crates/mrc_decoder",
    "crates/mrc_dos",
    "crates/mrc_emulator",
    "crates/mrc_encoder",
    "crates/mrc_screen",
    "crates/mrc_x86",
]
