[package]
name = "my-rusty-computer"
version = "0.1.0"
authors = ["Tiaan Louw <tiaanl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mrc"
path = "src/lib.rs"

[[bin]]
name = "mrc-dis"
path = "src/bin/mrc-dis.rs"

[[bin]]
name = "mrc-emu"
path = "src/bin/mrc-emu.rs"

[dependencies]
