[package]
name = "mrc-emu"
version = "0.0.1"
edition = "2018"

[features]
dos = []

[dependencies]
mrc_x86 = { path = "../../crates/mrc_x86" }
mrc_decoder = { path = "../../crates/mrc_decoder" }
mrc_dos = { path = "../../crates/mrc_dos" }
bitflags = "1.3.2"
byteorder = "1.4.3"
clap = "2"
sdl2 = { version = "0.34", features = ["bundled"] }
