[package]
name = "mrc-emu"
version = "0.0.1"
edition = "2018"

[features]
dos = []

[dependencies]
mrc_x86 = { path = "../../crates/mrc_x86" }
mrc_decoder = { path = "../../crates/mrc_decoder" }
mrc_dos = { path = "../../crates/mrc_dos" }
clap = "2"
byteorder = "1.4.3"
