[package]
name = "mrc-emu"
version = "0.0.1"
edition = "2018"

[dependencies]
mrc_x86 = { path = "../../crates/mrc_x86" }
mrc_decoder = { path = "../../crates/mrc_decoder" }
clap = "2.33.3"
byteorder = "1.4.3"
