[package]
name = "mrc-dis"
version = "0.0.1"
edition = "2021"

[dependencies]
mrc_decoder = { path = "../../crates/mrc_decoder" }
mrc_instruction = { path = "../../crates/mrc_instruction" }
clap = "2"
