[package]
name = "mrc_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
mrc_decoder = { path = "../mrc_decoder" }
mrc_instruction = { path = "../mrc_instruction" }
mrc_parser = { path = "../mrc_parser" }
