[package]
name = "mrc_emulator"
version = "0.0.1"
edition = "2018"

[dependencies]
mrc_decoder = { path = "../mrc_decoder" }
mrc_x86 = { path = "../mrc_x86" }
bitflags = "1.3"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
